//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	IcaaBearerAuthScopes = "icaaBearerAuth.Scopes"
	IcaaCookieAuthScopes = "icaaCookieAuth.Scopes"
)

// Defines values for ArticleStatus.
const (
	Draft     ArticleStatus = "draft"
	Published ArticleStatus = "published"
)

// Valid indicates whether the value is a known member of the ArticleStatus enum.
func (e ArticleStatus) Valid() bool {
	switch e {
	case Draft:
		return true
	case Published:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	AlreadyExists        ErrorCode = "AlreadyExists"
	AuthError            ErrorCode = "AuthError"
	EmptyBody            ErrorCode = "EmptyBody"
	InputValidationError ErrorCode = "InputValidationError"
	InternalError        ErrorCode = "InternalError"
	InvalidBody          ErrorCode = "InvalidBody"
	InvalidCursor        ErrorCode = "InvalidCursor"
	LimitOutOfBounds     ErrorCode = "LimitOutOfBounds"
	NotFound             ErrorCode = "NotFound"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case AlreadyExists:
		return true
	case AuthError:
		return true
	case EmptyBody:
		return true
	case InputValidationError:
		return true
	case InternalError:
		return true
	case InvalidBody:
		return true
	case InvalidCursor:
		return true
	case LimitOutOfBounds:
		return true
	case NotFound:
		return true
	default:
		return false
	}
}

// Article defines model for Article.
type Article struct {
	// Author Email of the admin who created the article
	Author *string `json:"author,omitempty"`

	// Content Editor.js JSON block data
	Content   map[string]interface{} `json:"content"`
	CreatedAt *time.Time             `json:"createdAt,omitempty"`
	Excerpt   string                 `json:"excerpt"`

	// PublishedAt When the article was published, null if draft
	PublishedAt *time.Time `json:"publishedAt,omitempty"`

	// Slug URL-friendly slug, immutable after creation
	Slug      string        `json:"slug"`
	Status    ArticleStatus `json:"status"`
	Title     string        `json:"title"`
	UpdatedAt *time.Time    `json:"updatedAt,omitempty"`
	Version   *int          `json:"version,omitempty"`
}

// ArticleStatus defines model for ArticleStatus.
type ArticleStatus string

// CreateArticleRequest defines model for CreateArticleRequest.
type CreateArticleRequest struct {
	Content map[string]interface{} `json:"content"`
	Excerpt string                 `json:"excerpt"`
	Slug    string                 `json:"slug"`
	Title   string                 `json:"title"`
}

// Error defines model for Error.
type Error struct {
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// UpdateArticleRequest defines model for UpdateArticleRequest.
type UpdateArticleRequest struct {
	Content *map[string]interface{} `json:"content,omitempty"`
	Excerpt *string                 `json:"excerpt,omitempty"`
	Title   *string                 `json:"title,omitempty"`
}

// GetArticlesV1Params defines parameters for GetArticlesV1.
type GetArticlesV1Params struct {
	// Cursor Cursor for pagination
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Max number of articles to fetch
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetArticlesV1AdminParams defines parameters for GetArticlesV1Admin.
type GetArticlesV1AdminParams struct {
	// Cursor Cursor for pagination
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Max number of articles to fetch
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostArticlesV1JSONRequestBody defines body for PostArticlesV1 for application/json ContentType.
type PostArticlesV1JSONRequestBody = CreateArticleRequest

// PatchArticlesV1SlugJSONRequestBody defines body for PatchArticlesV1Slug for application/json ContentType.
type PatchArticlesV1SlugJSONRequestBody = UpdateArticleRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List published articles
	// (GET /articles/v1)
	GetArticlesV1(w http.ResponseWriter, r *http.Request, params GetArticlesV1Params)
	// Create a new article
	// (POST /articles/v1)
	PostArticlesV1(w http.ResponseWriter, r *http.Request)
	// List all articles (admin)
	// (GET /articles/v1/admin)
	GetArticlesV1Admin(w http.ResponseWriter, r *http.Request, params GetArticlesV1AdminParams)
	// Delete an article
	// (DELETE /articles/v1/{slug})
	DeleteArticlesV1Slug(w http.ResponseWriter, r *http.Request, slug string)
	// Get a published article by slug
	// (GET /articles/v1/{slug})
	GetArticlesV1Slug(w http.ResponseWriter, r *http.Request, slug string)
	// Update an article
	// (PATCH /articles/v1/{slug})
	PatchArticlesV1Slug(w http.ResponseWriter, r *http.Request, slug string)
	// Publish an article
	// (POST /articles/v1/{slug}/publish)
	PostArticlesV1SlugPublish(w http.ResponseWriter, r *http.Request, slug string)
	// Unpublish an article
	// (POST /articles/v1/{slug}/unpublish)
	PostArticlesV1SlugUnpublish(w http.ResponseWriter, r *http.Request, slug string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetArticlesV1 operation middleware
func (siw *ServerInterfaceWrapper) GetArticlesV1(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetArticlesV1Params

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArticlesV1(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostArticlesV1 operation middleware
func (siw *ServerInterfaceWrapper) PostArticlesV1(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, IcaaCookieAuthScopes, []string{"admin"})

	ctx = context.WithValue(ctx, IcaaBearerAuthScopes, []string{"admin"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostArticlesV1(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArticlesV1Admin operation middleware
func (siw *ServerInterfaceWrapper) GetArticlesV1Admin(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, IcaaCookieAuthScopes, []string{"admin"})

	ctx = context.WithValue(ctx, IcaaBearerAuthScopes, []string{"admin"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetArticlesV1AdminParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArticlesV1Admin(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteArticlesV1Slug operation middleware
func (siw *ServerInterfaceWrapper) DeleteArticlesV1Slug(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, IcaaCookieAuthScopes, []string{"admin"})

	ctx = context.WithValue(ctx, IcaaBearerAuthScopes, []string{"admin"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteArticlesV1Slug(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArticlesV1Slug operation middleware
func (siw *ServerInterfaceWrapper) GetArticlesV1Slug(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArticlesV1Slug(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchArticlesV1Slug operation middleware
func (siw *ServerInterfaceWrapper) PatchArticlesV1Slug(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, IcaaCookieAuthScopes, []string{"admin"})

	ctx = context.WithValue(ctx, IcaaBearerAuthScopes, []string{"admin"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchArticlesV1Slug(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostArticlesV1SlugPublish operation middleware
func (siw *ServerInterfaceWrapper) PostArticlesV1SlugPublish(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, IcaaCookieAuthScopes, []string{"admin"})

	ctx = context.WithValue(ctx, IcaaBearerAuthScopes, []string{"admin"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostArticlesV1SlugPublish(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostArticlesV1SlugUnpublish operation middleware
func (siw *ServerInterfaceWrapper) PostArticlesV1SlugUnpublish(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, IcaaCookieAuthScopes, []string{"admin"})

	ctx = context.WithValue(ctx, IcaaBearerAuthScopes, []string{"admin"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostArticlesV1SlugUnpublish(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/articles/v1", wrapper.GetArticlesV1)
	m.HandleFunc("POST "+options.BaseURL+"/articles/v1", wrapper.PostArticlesV1)
	m.HandleFunc("GET "+options.BaseURL+"/articles/v1/admin", wrapper.GetArticlesV1Admin)
	m.HandleFunc("DELETE "+options.BaseURL+"/articles/v1/{slug}", wrapper.DeleteArticlesV1Slug)
	m.HandleFunc("GET "+options.BaseURL+"/articles/v1/{slug}", wrapper.GetArticlesV1Slug)
	m.HandleFunc("PATCH "+options.BaseURL+"/articles/v1/{slug}", wrapper.PatchArticlesV1Slug)
	m.HandleFunc("POST "+options.BaseURL+"/articles/v1/{slug}/publish", wrapper.PostArticlesV1SlugPublish)
	m.HandleFunc("POST "+options.BaseURL+"/articles/v1/{slug}/unpublish", wrapper.PostArticlesV1SlugUnpublish)

	return m
}

type GetArticlesV1RequestObject struct {
	Params GetArticlesV1Params
}

type GetArticlesV1ResponseObject interface {
	VisitGetArticlesV1Response(w http.ResponseWriter) error
}

type GetArticlesV1200JSONResponse struct {
	Cursor      *string   `json:"cursor,omitempty"`
	Data        []Article `json:"data"`
	HasNextPage bool      `json:"hasNextPage"`
}

func (response GetArticlesV1200JSONResponse) VisitGetArticlesV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetArticlesV1400JSONResponse Error

func (response GetArticlesV1400JSONResponse) VisitGetArticlesV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetArticlesV1500JSONResponse Error

func (response GetArticlesV1500JSONResponse) VisitGetArticlesV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostArticlesV1RequestObject struct {
	Body *PostArticlesV1JSONRequestBody
}

type PostArticlesV1ResponseObject interface {
	VisitPostArticlesV1Response(w http.ResponseWriter) error
}

type PostArticlesV1201JSONResponse struct {
	Article Article `json:"article"`
}

func (response PostArticlesV1201JSONResponse) VisitPostArticlesV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostArticlesV1400JSONResponse Error

func (response PostArticlesV1400JSONResponse) VisitPostArticlesV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostArticlesV1401JSONResponse Error

func (response PostArticlesV1401JSONResponse) VisitPostArticlesV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostArticlesV1409JSONResponse Error

func (response PostArticlesV1409JSONResponse) VisitPostArticlesV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PostArticlesV1500JSONResponse Error

func (response PostArticlesV1500JSONResponse) VisitPostArticlesV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetArticlesV1AdminRequestObject struct {
	Params GetArticlesV1AdminParams
}

type GetArticlesV1AdminResponseObject interface {
	VisitGetArticlesV1AdminResponse(w http.ResponseWriter) error
}

type GetArticlesV1Admin200JSONResponse struct {
	Cursor      *string   `json:"cursor,omitempty"`
	Data        []Article `json:"data"`
	HasNextPage bool      `json:"hasNextPage"`
}

func (response GetArticlesV1Admin200JSONResponse) VisitGetArticlesV1AdminResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetArticlesV1Admin400JSONResponse Error

func (response GetArticlesV1Admin400JSONResponse) VisitGetArticlesV1AdminResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetArticlesV1Admin401JSONResponse Error

func (response GetArticlesV1Admin401JSONResponse) VisitGetArticlesV1AdminResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetArticlesV1Admin500JSONResponse Error

func (response GetArticlesV1Admin500JSONResponse) VisitGetArticlesV1AdminResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteArticlesV1SlugRequestObject struct {
	Slug string `json:"slug"`
}

type DeleteArticlesV1SlugResponseObject interface {
	VisitDeleteArticlesV1SlugResponse(w http.ResponseWriter) error
}

type DeleteArticlesV1Slug204Response struct {
}

func (response DeleteArticlesV1Slug204Response) VisitDeleteArticlesV1SlugResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteArticlesV1Slug401JSONResponse Error

func (response DeleteArticlesV1Slug401JSONResponse) VisitDeleteArticlesV1SlugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteArticlesV1Slug404JSONResponse Error

func (response DeleteArticlesV1Slug404JSONResponse) VisitDeleteArticlesV1SlugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteArticlesV1Slug500JSONResponse Error

func (response DeleteArticlesV1Slug500JSONResponse) VisitDeleteArticlesV1SlugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetArticlesV1SlugRequestObject struct {
	Slug string `json:"slug"`
}

type GetArticlesV1SlugResponseObject interface {
	VisitGetArticlesV1SlugResponse(w http.ResponseWriter) error
}

type GetArticlesV1Slug200JSONResponse struct {
	Article Article `json:"article"`
}

func (response GetArticlesV1Slug200JSONResponse) VisitGetArticlesV1SlugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetArticlesV1Slug404JSONResponse Error

func (response GetArticlesV1Slug404JSONResponse) VisitGetArticlesV1SlugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetArticlesV1Slug500JSONResponse Error

func (response GetArticlesV1Slug500JSONResponse) VisitGetArticlesV1SlugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PatchArticlesV1SlugRequestObject struct {
	Slug string `json:"slug"`
	Body *PatchArticlesV1SlugJSONRequestBody
}

type PatchArticlesV1SlugResponseObject interface {
	VisitPatchArticlesV1SlugResponse(w http.ResponseWriter) error
}

type PatchArticlesV1Slug200JSONResponse struct {
	Article Article `json:"article"`
}

func (response PatchArticlesV1Slug200JSONResponse) VisitPatchArticlesV1SlugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PatchArticlesV1Slug400JSONResponse Error

func (response PatchArticlesV1Slug400JSONResponse) VisitPatchArticlesV1SlugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PatchArticlesV1Slug401JSONResponse Error

func (response PatchArticlesV1Slug401JSONResponse) VisitPatchArticlesV1SlugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PatchArticlesV1Slug404JSONResponse Error

func (response PatchArticlesV1Slug404JSONResponse) VisitPatchArticlesV1SlugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PatchArticlesV1Slug500JSONResponse Error

func (response PatchArticlesV1Slug500JSONResponse) VisitPatchArticlesV1SlugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostArticlesV1SlugPublishRequestObject struct {
	Slug string `json:"slug"`
}

type PostArticlesV1SlugPublishResponseObject interface {
	VisitPostArticlesV1SlugPublishResponse(w http.ResponseWriter) error
}

type PostArticlesV1SlugPublish200JSONResponse struct {
	Article Article `json:"article"`
}

func (response PostArticlesV1SlugPublish200JSONResponse) VisitPostArticlesV1SlugPublishResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostArticlesV1SlugPublish401JSONResponse Error

func (response PostArticlesV1SlugPublish401JSONResponse) VisitPostArticlesV1SlugPublishResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostArticlesV1SlugPublish404JSONResponse Error

func (response PostArticlesV1SlugPublish404JSONResponse) VisitPostArticlesV1SlugPublishResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostArticlesV1SlugPublish500JSONResponse Error

func (response PostArticlesV1SlugPublish500JSONResponse) VisitPostArticlesV1SlugPublishResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostArticlesV1SlugUnpublishRequestObject struct {
	Slug string `json:"slug"`
}

type PostArticlesV1SlugUnpublishResponseObject interface {
	VisitPostArticlesV1SlugUnpublishResponse(w http.ResponseWriter) error
}

type PostArticlesV1SlugUnpublish200JSONResponse struct {
	Article Article `json:"article"`
}

func (response PostArticlesV1SlugUnpublish200JSONResponse) VisitPostArticlesV1SlugUnpublishResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostArticlesV1SlugUnpublish401JSONResponse Error

func (response PostArticlesV1SlugUnpublish401JSONResponse) VisitPostArticlesV1SlugUnpublishResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostArticlesV1SlugUnpublish404JSONResponse Error

func (response PostArticlesV1SlugUnpublish404JSONResponse) VisitPostArticlesV1SlugUnpublishResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostArticlesV1SlugUnpublish500JSONResponse Error

func (response PostArticlesV1SlugUnpublish500JSONResponse) VisitPostArticlesV1SlugUnpublishResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List published articles
	// (GET /articles/v1)
	GetArticlesV1(ctx context.Context, request GetArticlesV1RequestObject) (GetArticlesV1ResponseObject, error)
	// Create a new article
	// (POST /articles/v1)
	PostArticlesV1(ctx context.Context, request PostArticlesV1RequestObject) (PostArticlesV1ResponseObject, error)
	// List all articles (admin)
	// (GET /articles/v1/admin)
	GetArticlesV1Admin(ctx context.Context, request GetArticlesV1AdminRequestObject) (GetArticlesV1AdminResponseObject, error)
	// Delete an article
	// (DELETE /articles/v1/{slug})
	DeleteArticlesV1Slug(ctx context.Context, request DeleteArticlesV1SlugRequestObject) (DeleteArticlesV1SlugResponseObject, error)
	// Get a published article by slug
	// (GET /articles/v1/{slug})
	GetArticlesV1Slug(ctx context.Context, request GetArticlesV1SlugRequestObject) (GetArticlesV1SlugResponseObject, error)
	// Update an article
	// (PATCH /articles/v1/{slug})
	PatchArticlesV1Slug(ctx context.Context, request PatchArticlesV1SlugRequestObject) (PatchArticlesV1SlugResponseObject, error)
	// Publish an article
	// (POST /articles/v1/{slug}/publish)
	PostArticlesV1SlugPublish(ctx context.Context, request PostArticlesV1SlugPublishRequestObject) (PostArticlesV1SlugPublishResponseObject, error)
	// Unpublish an article
	// (POST /articles/v1/{slug}/unpublish)
	PostArticlesV1SlugUnpublish(ctx context.Context, request PostArticlesV1SlugUnpublishRequestObject) (PostArticlesV1SlugUnpublishResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetArticlesV1 operation middleware
func (sh *strictHandler) GetArticlesV1(w http.ResponseWriter, r *http.Request, params GetArticlesV1Params) {
	var request GetArticlesV1RequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetArticlesV1(ctx, request.(GetArticlesV1RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetArticlesV1")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetArticlesV1ResponseObject); ok {
		if err := validResponse.VisitGetArticlesV1Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostArticlesV1 operation middleware
func (sh *strictHandler) PostArticlesV1(w http.ResponseWriter, r *http.Request) {
	var request PostArticlesV1RequestObject

	var body PostArticlesV1JSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostArticlesV1(ctx, request.(PostArticlesV1RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostArticlesV1")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostArticlesV1ResponseObject); ok {
		if err := validResponse.VisitPostArticlesV1Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetArticlesV1Admin operation middleware
func (sh *strictHandler) GetArticlesV1Admin(w http.ResponseWriter, r *http.Request, params GetArticlesV1AdminParams) {
	var request GetArticlesV1AdminRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetArticlesV1Admin(ctx, request.(GetArticlesV1AdminRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetArticlesV1Admin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetArticlesV1AdminResponseObject); ok {
		if err := validResponse.VisitGetArticlesV1AdminResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteArticlesV1Slug operation middleware
func (sh *strictHandler) DeleteArticlesV1Slug(w http.ResponseWriter, r *http.Request, slug string) {
	var request DeleteArticlesV1SlugRequestObject

	request.Slug = slug

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteArticlesV1Slug(ctx, request.(DeleteArticlesV1SlugRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteArticlesV1Slug")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteArticlesV1SlugResponseObject); ok {
		if err := validResponse.VisitDeleteArticlesV1SlugResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetArticlesV1Slug operation middleware
func (sh *strictHandler) GetArticlesV1Slug(w http.ResponseWriter, r *http.Request, slug string) {
	var request GetArticlesV1SlugRequestObject

	request.Slug = slug

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetArticlesV1Slug(ctx, request.(GetArticlesV1SlugRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetArticlesV1Slug")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetArticlesV1SlugResponseObject); ok {
		if err := validResponse.VisitGetArticlesV1SlugResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchArticlesV1Slug operation middleware
func (sh *strictHandler) PatchArticlesV1Slug(w http.ResponseWriter, r *http.Request, slug string) {
	var request PatchArticlesV1SlugRequestObject

	request.Slug = slug

	var body PatchArticlesV1SlugJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchArticlesV1Slug(ctx, request.(PatchArticlesV1SlugRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchArticlesV1Slug")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchArticlesV1SlugResponseObject); ok {
		if err := validResponse.VisitPatchArticlesV1SlugResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostArticlesV1SlugPublish operation middleware
func (sh *strictHandler) PostArticlesV1SlugPublish(w http.ResponseWriter, r *http.Request, slug string) {
	var request PostArticlesV1SlugPublishRequestObject

	request.Slug = slug

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostArticlesV1SlugPublish(ctx, request.(PostArticlesV1SlugPublishRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostArticlesV1SlugPublish")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostArticlesV1SlugPublishResponseObject); ok {
		if err := validResponse.VisitPostArticlesV1SlugPublishResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostArticlesV1SlugUnpublish operation middleware
func (sh *strictHandler) PostArticlesV1SlugUnpublish(w http.ResponseWriter, r *http.Request, slug string) {
	var request PostArticlesV1SlugUnpublishRequestObject

	request.Slug = slug

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostArticlesV1SlugUnpublish(ctx, request.(PostArticlesV1SlugUnpublishRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostArticlesV1SlugUnpublish")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostArticlesV1SlugUnpublishResponseObject); ok {
		if err := validResponse.VisitPostArticlesV1SlugUnpublishResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaf3PbNhL9KhhcZ669oyTKjmcunOnc0arjOnVjT/wjc/b4OhC5EhGTAAOAtpWMvvvN",
	"AqRISqxlpW7dpP5PJBfAYrHv7VvYn2gks1wKEEbT4BPVUQIZsz9DZXiUAv7MlcxBGQ72AytMIhX+ikFH",
	"iueGS0EDupcxnhI5ISYBwuKMC3KbSBIpYAZi97ac06Nwx7IcZ6fW8j88Yqx/K1UaU48qYPGRSGc0MKoA",
	"j5pZjpbaKC6mdO7RSAoDwnT4EHMjVf+9Jq9Pjt6QcSqjaxIzw+hiFjl+D5GxszjPQjtP7dCWv7XT8//V",
	"23p5OtwKfD/w/Qvq0YlUGTM0oDEz0DM8g4d4CncRqHxphdMEyMEoDAnXJFeyiImRhAkhCxEB4UYTOZnw",
	"iLOUpKwQUdLv96lHM3Z3CGJqEhoMfd/3aMbF4kXH2nkxTrlOqh22I/UuAdE8E3LLNFmM8Igo0pTwCYkV",
	"m5jWgW0SH5yFjXGYi8/aeOm0mK46e/b2sDdRHESczgiaeIRnWWFwasImBpRLM7RuuopZ1XMhbMdvazV8",
	"OTMGFK72v0vW+xj2Lvzey6t/fvvvoNd8/u4f39Auvw0zhYXHNwomNKB/G9TIGpSwGpSYOnHGc48abhzE",
	"ap9tYhxan0lY5kSGyd7awM4Dzr/I4/vye9s/He4E278tv29AaXtGjRWGvzqOCwNTUHQ+R5MPBVcQ0+DS",
	"nXoVjRo0NdAXAfYq+mnCt7nV2qWrDsi3DwCdFkWGHlRpvkAADq9jVr/uiMHIOlJO/RY+FKDNKm02OGvF",
	"radkiQpxT4Ga3zH9N82wrmzZU8oVuuWTjGEd0u3QERrOPZqB1my6tNFQkELAXQ4RVkdAeyKjqFAK4j5d",
	"tx/rQz3zr3o/Kn2t8vxA4HGx1G3No4c84+aoMEeTXVmIGAF2IG5YyuNRobQ1eSPNK/xGPbqX5Wa2K+NZ",
	"bVY+hSlCfrZ3x7Vxk+SFOUcDy8rVcmFhEvf7qiMdziyKHwlIm+KgIxedPzF5xJxc8hjxB1GhuJmdYOa4",
	"HSIAd4EpUBgvfDO2T68qin797pR6SzXSOsmiCLQmRl6DIFyQ0JIl/2gPgSTAYsBjsFmKfrh562xLjMkx",
	"GOjBSMprDpUH6xaLrDX1KMfviyfBsgrVv4Sj0d7JyS+nRz/tvamXZDn/CWZ0jrHgYiJXFwsFCY8PyEQq",
	"kjHBplxMK9Wi7VtTMeUtjDU30F8gvfQ0rKzD44NGhQjosO/3fdywzEGwnNOAbttXltkSexqDaq3BzRCf",
	"p9Ahp96CURxuQBNGcnTRJk7KtUFFvCgftd9aKrQYz8iidhGcEkTMxRR3gDlvz+0gpgHdB1Pt4nxo3VMs",
	"AwNK0+By2RuHXRub0hmnjOzZfChAzeqjiSqcO+pqI+C/Wy+Li+3XSfzjz/rgx/QmPtnNxtvnxcVo12f7",
	"Z9OLd68+xvvns4P9c3Fx+/33Xby17NzP7I6IIhuDwtAsAmIkmYCxJafLzRSJquVlDBNWpAbh3SjV+JCx",
	"O54h3+04RLqHYYcMuUJW1bkU2iFvy/eXKIblecojG8DBe+2UTu3DEjO5UD5yBD1qGxjkBQPZQzUmrcmG",
	"KcVm+Jww/QbuzPFyLWpptLGUKTCxUnHKLqo5x2rVwUFL4L0HBH106sWGIV9bdbu82GUxUa6g2EV3/ohF",
	"z8S1kLeCaFA3oFyJ77c4nwaXVx7VRZYxNaMBPcRQrcbJNnNSd9COk55IOgJuK/s++cFBw4LKKlvi5HOf",
	"hLYvlyKdrVLMsdRtjikjZkv8Y0WrUyx35U3ZllZ9HYnBMJ5q2sxKTNz5CoSHvwHCrL71eBDIlkBSDX8Q",
	"Mpo7hJjowtbTSZHi4TwVMl5sGL7PRAYrhQlqXbvqy99/1Srgt9wkxCRc26sEwpx0JWC165+MHj6tSLFL",
	"d2NGr7CyLivF+mOLVxzo2ixhV2pqm4Eb+nkKh6VpXcq/dZzDRFyT2XfrFM+91NRSP9bwWQI9S6AvTgI1",
	"UfJXo/ivjVOtVmvTnrX7bpVYP2GdmTvApmBglVx/sO81YWJxHz92N93386IbV1PjibvmWmJGSybYz9Zc",
	"Ut6HtaVUNwG2rwOXuW2VPl50dPDlntz2O6XO06iOF3+c6hDSkIksxNeJBpeIjfzFTa7VEZqLaQqrHQ8m",
	"PzdOn60RA3+GjPe/jIbjtP5r33P6d/bf+2BQ3Xalo02fub0WjDouRN1VsSVw20c07ijXNN0435On8+P3",
	"+Z13+ffkh+sJNujy/S+ryy97nr94l/9MOI9Ubx28WvW2W3UOSjazIOi8QzwB0xSef9flZSG2ow0qFDHR",
	"aGmSRsEODTE8A21Ylm9yuYg0d1w69ly8N+GR+kSeRfTXBuoSEQ9BdSE+H9djFl3XfxlAYEcpMPWI0D5b",
	"ePcM7o1EgniG91dcs6vTbQN87VLda7jJrddd99/HSsZFZP9y5oyoRwuVlv/joYPBgOW8X//b7YCuXlMf",
	"yoilJIabrimCwSDF74nUJtj2fX9A51fz/wcAAP//vq+lX1EsAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
