//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	IcaaBearerAuthScopes = "icaaBearerAuth.Scopes"
	IcaaCookieAuthScopes = "icaaCookieAuth.Scopes"
)

// Defines values for ArticleStatus.
const (
	Draft     ArticleStatus = "draft"
	Published ArticleStatus = "published"
)

// Valid indicates whether the value is a known member of the ArticleStatus enum.
func (e ArticleStatus) Valid() bool {
	switch e {
	case Draft:
		return true
	case Published:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	AlreadyExists        ErrorCode = "AlreadyExists"
	AuthError            ErrorCode = "AuthError"
	EmptyBody            ErrorCode = "EmptyBody"
	InputValidationError ErrorCode = "InputValidationError"
	InternalError        ErrorCode = "InternalError"
	InvalidBody          ErrorCode = "InvalidBody"
	InvalidCursor        ErrorCode = "InvalidCursor"
	LimitOutOfBounds     ErrorCode = "LimitOutOfBounds"
	NotFound             ErrorCode = "NotFound"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case AlreadyExists:
		return true
	case AuthError:
		return true
	case EmptyBody:
		return true
	case InputValidationError:
		return true
	case InternalError:
		return true
	case InvalidBody:
		return true
	case InvalidCursor:
		return true
	case LimitOutOfBounds:
		return true
	case NotFound:
		return true
	default:
		return false
	}
}

// Article defines model for Article.
type Article struct {
	// Author Email of the admin who created the article
	Author *string `json:"author,omitempty"`

	// Content Editor.js JSON block data
	Content   map[string]interface{} `json:"content"`
	CreatedAt *time.Time             `json:"createdAt,omitempty"`
	Excerpt   string                 `json:"excerpt"`

	// PublishedAt When the article was published, null if draft
	PublishedAt *time.Time `json:"publishedAt,omitempty"`

	// Slug URL-friendly slug, immutable after creation
	Slug      string        `json:"slug"`
	Status    ArticleStatus `json:"status"`
	Title     string        `json:"title"`
	UpdatedAt *time.Time    `json:"updatedAt,omitempty"`
	Version   *int          `json:"version,omitempty"`
}

// ArticleStatus defines model for ArticleStatus.
type ArticleStatus string

// CreateArticleRequest defines model for CreateArticleRequest.
type CreateArticleRequest struct {
	Content map[string]interface{} `json:"content"`
	Excerpt string                 `json:"excerpt"`
	Slug    string                 `json:"slug"`
	Title   string                 `json:"title"`
}

// Error defines model for Error.
type Error struct {
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// UpdateArticleRequest defines model for UpdateArticleRequest.
type UpdateArticleRequest struct {
	Content *map[string]interface{} `json:"content,omitempty"`
	Excerpt *string                 `json:"excerpt,omitempty"`
	Title   *string                 `json:"title,omitempty"`
}

// GetArticlesV1Params defines parameters for GetArticlesV1.
type GetArticlesV1Params struct {
	// Cursor Cursor for pagination
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Max number of articles to fetch
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetArticlesV1AdminParams defines parameters for GetArticlesV1Admin.
type GetArticlesV1AdminParams struct {
	// Cursor Cursor for pagination
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Max number of articles to fetch
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostArticlesV1JSONRequestBody defines body for PostArticlesV1 for application/json ContentType.
type PostArticlesV1JSONRequestBody = CreateArticleRequest

// PatchArticlesV1SlugJSONRequestBody defines body for PatchArticlesV1Slug for application/json ContentType.
type PatchArticlesV1SlugJSONRequestBody = UpdateArticleRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List published articles
	// (GET /articles/v1)
	GetArticlesV1(w http.ResponseWriter, r *http.Request, params GetArticlesV1Params)
	// Create a new article
	// (POST /articles/v1)
	PostArticlesV1(w http.ResponseWriter, r *http.Request)
	// List all articles (admin)
	// (GET /articles/v1/admin)
	GetArticlesV1Admin(w http.ResponseWriter, r *http.Request, params GetArticlesV1AdminParams)
	// Delete an article
	// (DELETE /articles/v1/{slug})
	DeleteArticlesV1Slug(w http.ResponseWriter, r *http.Request, slug string)
	// Get a published article by slug
	// (GET /articles/v1/{slug})
	GetArticlesV1Slug(w http.ResponseWriter, r *http.Request, slug string)
	// Update an article
	// (PATCH /articles/v1/{slug})
	PatchArticlesV1Slug(w http.ResponseWriter, r *http.Request, slug string)
	// Publish an article
	// (POST /articles/v1/{slug}/publish)
	PostArticlesV1SlugPublish(w http.ResponseWriter, r *http.Request, slug string)
	// Unpublish an article
	// (POST /articles/v1/{slug}/unpublish)
	PostArticlesV1SlugUnpublish(w http.ResponseWriter, r *http.Request, slug string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetArticlesV1 operation middleware
func (siw *ServerInterfaceWrapper) GetArticlesV1(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetArticlesV1Params

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArticlesV1(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostArticlesV1 operation middleware
func (siw *ServerInterfaceWrapper) PostArticlesV1(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, IcaaCookieAuthScopes, []string{"admin"})

	ctx = context.WithValue(ctx, IcaaBearerAuthScopes, []string{"admin"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostArticlesV1(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArticlesV1Admin operation middleware
func (siw *ServerInterfaceWrapper) GetArticlesV1Admin(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, IcaaCookieAuthScopes, []string{"admin"})

	ctx = context.WithValue(ctx, IcaaBearerAuthScopes, []string{"admin"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetArticlesV1AdminParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArticlesV1Admin(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteArticlesV1Slug operation middleware
func (siw *ServerInterfaceWrapper) DeleteArticlesV1Slug(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, IcaaCookieAuthScopes, []string{"admin"})

	ctx = context.WithValue(ctx, IcaaBearerAuthScopes, []string{"admin"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteArticlesV1Slug(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArticlesV1Slug operation middleware
func (siw *ServerInterfaceWrapper) GetArticlesV1Slug(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArticlesV1Slug(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchArticlesV1Slug operation middleware
func (siw *ServerInterfaceWrapper) PatchArticlesV1Slug(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, IcaaCookieAuthScopes, []string{"admin"})

	ctx = context.WithValue(ctx, IcaaBearerAuthScopes, []string{"admin"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchArticlesV1Slug(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostArticlesV1SlugPublish operation middleware
func (siw *ServerInterfaceWrapper) PostArticlesV1SlugPublish(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, IcaaCookieAuthScopes, []string{"admin"})

	ctx = context.WithValue(ctx, IcaaBearerAuthScopes, []string{"admin"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostArticlesV1SlugPublish(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostArticlesV1SlugUnpublish operation middleware
func (siw *ServerInterfaceWrapper) PostArticlesV1SlugUnpublish(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, IcaaCookieAuthScopes, []string{"admin"})

	ctx = context.WithValue(ctx, IcaaBearerAuthScopes, []string{"admin"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostArticlesV1SlugUnpublish(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/articles/v1", wrapper.GetArticlesV1)
	m.HandleFunc("POST "+options.BaseURL+"/articles/v1", wrapper.PostArticlesV1)
	m.HandleFunc("GET "+options.BaseURL+"/articles/v1/admin", wrapper.GetArticlesV1Admin)
	m.HandleFunc("DELETE "+options.BaseURL+"/articles/v1/{slug}", wrapper.DeleteArticlesV1Slug)
	m.HandleFunc("GET "+options.BaseURL+"/articles/v1/{slug}", wrapper.GetArticlesV1Slug)
	m.HandleFunc("PATCH "+options.BaseURL+"/articles/v1/{slug}", wrapper.PatchArticlesV1Slug)
	m.HandleFunc("POST "+options.BaseURL+"/articles/v1/{slug}/publish", wrapper.PostArticlesV1SlugPublish)
	m.HandleFunc("POST "+options.BaseURL+"/articles/v1/{slug}/unpublish", wrapper.PostArticlesV1SlugUnpublish)

	return m
}

type GetArticlesV1RequestObject struct {
	Params GetArticlesV1Params
}

type GetArticlesV1ResponseObject interface {
	VisitGetArticlesV1Response(w http.ResponseWriter) error
}

type GetArticlesV1200JSONResponse struct {
	Cursor      *string   `json:"cursor,omitempty"`
	Data        []Article `json:"data"`
	HasNextPage bool      `json:"hasNextPage"`
}

func (response GetArticlesV1200JSONResponse) VisitGetArticlesV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetArticlesV1400JSONResponse Error

func (response GetArticlesV1400JSONResponse) VisitGetArticlesV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetArticlesV1500JSONResponse Error

func (response GetArticlesV1500JSONResponse) VisitGetArticlesV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostArticlesV1RequestObject struct {
	Body *PostArticlesV1JSONRequestBody
}

type PostArticlesV1ResponseObject interface {
	VisitPostArticlesV1Response(w http.ResponseWriter) error
}

type PostArticlesV1201JSONResponse struct {
	Article Article `json:"article"`
}

func (response PostArticlesV1201JSONResponse) VisitPostArticlesV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostArticlesV1400JSONResponse Error

func (response PostArticlesV1400JSONResponse) VisitPostArticlesV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostArticlesV1401JSONResponse Error

func (response PostArticlesV1401JSONResponse) VisitPostArticlesV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostArticlesV1409JSONResponse Error

func (response PostArticlesV1409JSONResponse) VisitPostArticlesV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PostArticlesV1500JSONResponse Error

func (response PostArticlesV1500JSONResponse) VisitPostArticlesV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetArticlesV1AdminRequestObject struct {
	Params GetArticlesV1AdminParams
}

type GetArticlesV1AdminResponseObject interface {
	VisitGetArticlesV1AdminResponse(w http.ResponseWriter) error
}

type GetArticlesV1Admin200JSONResponse struct {
	Cursor      *string   `json:"cursor,omitempty"`
	Data        []Article `json:"data"`
	HasNextPage bool      `json:"hasNextPage"`
}

func (response GetArticlesV1Admin200JSONResponse) VisitGetArticlesV1AdminResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetArticlesV1Admin400JSONResponse Error

func (response GetArticlesV1Admin400JSONResponse) VisitGetArticlesV1AdminResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetArticlesV1Admin401JSONResponse Error

func (response GetArticlesV1Admin401JSONResponse) VisitGetArticlesV1AdminResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetArticlesV1Admin500JSONResponse Error

func (response GetArticlesV1Admin500JSONResponse) VisitGetArticlesV1AdminResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteArticlesV1SlugRequestObject struct {
	Slug string `json:"slug"`
}

type DeleteArticlesV1SlugResponseObject interface {
	VisitDeleteArticlesV1SlugResponse(w http.ResponseWriter) error
}

type DeleteArticlesV1Slug204Response struct {
}

func (response DeleteArticlesV1Slug204Response) VisitDeleteArticlesV1SlugResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteArticlesV1Slug401JSONResponse Error

func (response DeleteArticlesV1Slug401JSONResponse) VisitDeleteArticlesV1SlugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteArticlesV1Slug404JSONResponse Error

func (response DeleteArticlesV1Slug404JSONResponse) VisitDeleteArticlesV1SlugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteArticlesV1Slug500JSONResponse Error

func (response DeleteArticlesV1Slug500JSONResponse) VisitDeleteArticlesV1SlugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetArticlesV1SlugRequestObject struct {
	Slug string `json:"slug"`
}

type GetArticlesV1SlugResponseObject interface {
	VisitGetArticlesV1SlugResponse(w http.ResponseWriter) error
}

type GetArticlesV1Slug200JSONResponse struct {
	Article Article `json:"article"`
}

func (response GetArticlesV1Slug200JSONResponse) VisitGetArticlesV1SlugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetArticlesV1Slug404JSONResponse Error

func (response GetArticlesV1Slug404JSONResponse) VisitGetArticlesV1SlugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetArticlesV1Slug500JSONResponse Error

func (response GetArticlesV1Slug500JSONResponse) VisitGetArticlesV1SlugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PatchArticlesV1SlugRequestObject struct {
	Slug string `json:"slug"`
	Body *PatchArticlesV1SlugJSONRequestBody
}

type PatchArticlesV1SlugResponseObject interface {
	VisitPatchArticlesV1SlugResponse(w http.ResponseWriter) error
}

type PatchArticlesV1Slug200JSONResponse struct {
	Article Article `json:"article"`
}

func (response PatchArticlesV1Slug200JSONResponse) VisitPatchArticlesV1SlugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PatchArticlesV1Slug400JSONResponse Error

func (response PatchArticlesV1Slug400JSONResponse) VisitPatchArticlesV1SlugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PatchArticlesV1Slug401JSONResponse Error

func (response PatchArticlesV1Slug401JSONResponse) VisitPatchArticlesV1SlugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PatchArticlesV1Slug404JSONResponse Error

func (response PatchArticlesV1Slug404JSONResponse) VisitPatchArticlesV1SlugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PatchArticlesV1Slug500JSONResponse Error

func (response PatchArticlesV1Slug500JSONResponse) VisitPatchArticlesV1SlugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostArticlesV1SlugPublishRequestObject struct {
	Slug string `json:"slug"`
}

type PostArticlesV1SlugPublishResponseObject interface {
	VisitPostArticlesV1SlugPublishResponse(w http.ResponseWriter) error
}

type PostArticlesV1SlugPublish200JSONResponse struct {
	Article Article `json:"article"`
}

func (response PostArticlesV1SlugPublish200JSONResponse) VisitPostArticlesV1SlugPublishResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostArticlesV1SlugPublish401JSONResponse Error

func (response PostArticlesV1SlugPublish401JSONResponse) VisitPostArticlesV1SlugPublishResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostArticlesV1SlugPublish404JSONResponse Error

func (response PostArticlesV1SlugPublish404JSONResponse) VisitPostArticlesV1SlugPublishResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostArticlesV1SlugPublish500JSONResponse Error

func (response PostArticlesV1SlugPublish500JSONResponse) VisitPostArticlesV1SlugPublishResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostArticlesV1SlugUnpublishRequestObject struct {
	Slug string `json:"slug"`
}

type PostArticlesV1SlugUnpublishResponseObject interface {
	VisitPostArticlesV1SlugUnpublishResponse(w http.ResponseWriter) error
}

type PostArticlesV1SlugUnpublish200JSONResponse struct {
	Article Article `json:"article"`
}

func (response PostArticlesV1SlugUnpublish200JSONResponse) VisitPostArticlesV1SlugUnpublishResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostArticlesV1SlugUnpublish401JSONResponse Error

func (response PostArticlesV1SlugUnpublish401JSONResponse) VisitPostArticlesV1SlugUnpublishResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostArticlesV1SlugUnpublish404JSONResponse Error

func (response PostArticlesV1SlugUnpublish404JSONResponse) VisitPostArticlesV1SlugUnpublishResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostArticlesV1SlugUnpublish500JSONResponse Error

func (response PostArticlesV1SlugUnpublish500JSONResponse) VisitPostArticlesV1SlugUnpublishResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List published articles
	// (GET /articles/v1)
	GetArticlesV1(ctx context.Context, request GetArticlesV1RequestObject) (GetArticlesV1ResponseObject, error)
	// Create a new article
	// (POST /articles/v1)
	PostArticlesV1(ctx context.Context, request PostArticlesV1RequestObject) (PostArticlesV1ResponseObject, error)
	// List all articles (admin)
	// (GET /articles/v1/admin)
	GetArticlesV1Admin(ctx context.Context, request GetArticlesV1AdminRequestObject) (GetArticlesV1AdminResponseObject, error)
	// Delete an article
	// (DELETE /articles/v1/{slug})
	DeleteArticlesV1Slug(ctx context.Context, request DeleteArticlesV1SlugRequestObject) (DeleteArticlesV1SlugResponseObject, error)
	// Get a published article by slug
	// (GET /articles/v1/{slug})
	GetArticlesV1Slug(ctx context.Context, request GetArticlesV1SlugRequestObject) (GetArticlesV1SlugResponseObject, error)
	// Update an article
	// (PATCH /articles/v1/{slug})
	PatchArticlesV1Slug(ctx context.Context, request PatchArticlesV1SlugRequestObject) (PatchArticlesV1SlugResponseObject, error)
	// Publish an article
	// (POST /articles/v1/{slug}/publish)
	PostArticlesV1SlugPublish(ctx context.Context, request PostArticlesV1SlugPublishRequestObject) (PostArticlesV1SlugPublishResponseObject, error)
	// Unpublish an article
	// (POST /articles/v1/{slug}/unpublish)
	PostArticlesV1SlugUnpublish(ctx context.Context, request PostArticlesV1SlugUnpublishRequestObject) (PostArticlesV1SlugUnpublishResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetArticlesV1 operation middleware
func (sh *strictHandler) GetArticlesV1(w http.ResponseWriter, r *http.Request, params GetArticlesV1Params) {
	var request GetArticlesV1RequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetArticlesV1(ctx, request.(GetArticlesV1RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetArticlesV1")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetArticlesV1ResponseObject); ok {
		if err := validResponse.VisitGetArticlesV1Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostArticlesV1 operation middleware
func (sh *strictHandler) PostArticlesV1(w http.ResponseWriter, r *http.Request) {
	var request PostArticlesV1RequestObject

	var body PostArticlesV1JSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostArticlesV1(ctx, request.(PostArticlesV1RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostArticlesV1")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostArticlesV1ResponseObject); ok {
		if err := validResponse.VisitPostArticlesV1Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetArticlesV1Admin operation middleware
func (sh *strictHandler) GetArticlesV1Admin(w http.ResponseWriter, r *http.Request, params GetArticlesV1AdminParams) {
	var request GetArticlesV1AdminRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetArticlesV1Admin(ctx, request.(GetArticlesV1AdminRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetArticlesV1Admin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetArticlesV1AdminResponseObject); ok {
		if err := validResponse.VisitGetArticlesV1AdminResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteArticlesV1Slug operation middleware
func (sh *strictHandler) DeleteArticlesV1Slug(w http.ResponseWriter, r *http.Request, slug string) {
	var request DeleteArticlesV1SlugRequestObject

	request.Slug = slug

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteArticlesV1Slug(ctx, request.(DeleteArticlesV1SlugRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteArticlesV1Slug")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteArticlesV1SlugResponseObject); ok {
		if err := validResponse.VisitDeleteArticlesV1SlugResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetArticlesV1Slug operation middleware
func (sh *strictHandler) GetArticlesV1Slug(w http.ResponseWriter, r *http.Request, slug string) {
	var request GetArticlesV1SlugRequestObject

	request.Slug = slug

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetArticlesV1Slug(ctx, request.(GetArticlesV1SlugRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetArticlesV1Slug")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetArticlesV1SlugResponseObject); ok {
		if err := validResponse.VisitGetArticlesV1SlugResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchArticlesV1Slug operation middleware
func (sh *strictHandler) PatchArticlesV1Slug(w http.ResponseWriter, r *http.Request, slug string) {
	var request PatchArticlesV1SlugRequestObject

	request.Slug = slug

	var body PatchArticlesV1SlugJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchArticlesV1Slug(ctx, request.(PatchArticlesV1SlugRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchArticlesV1Slug")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchArticlesV1SlugResponseObject); ok {
		if err := validResponse.VisitPatchArticlesV1SlugResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostArticlesV1SlugPublish operation middleware
func (sh *strictHandler) PostArticlesV1SlugPublish(w http.ResponseWriter, r *http.Request, slug string) {
	var request PostArticlesV1SlugPublishRequestObject

	request.Slug = slug

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostArticlesV1SlugPublish(ctx, request.(PostArticlesV1SlugPublishRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostArticlesV1SlugPublish")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostArticlesV1SlugPublishResponseObject); ok {
		if err := validResponse.VisitPostArticlesV1SlugPublishResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostArticlesV1SlugUnpublish operation middleware
func (sh *strictHandler) PostArticlesV1SlugUnpublish(w http.ResponseWriter, r *http.Request, slug string) {
	var request PostArticlesV1SlugUnpublishRequestObject

	request.Slug = slug

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostArticlesV1SlugUnpublish(ctx, request.(PostArticlesV1SlugUnpublishRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostArticlesV1SlugUnpublish")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostArticlesV1SlugUnpublishResponseObject); ok {
		if err := validResponse.VisitPostArticlesV1SlugUnpublishResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaf2/bOBL9KgRvgdveybacNMBVwOLO8abZdLNN0PwoLkFuQUtji41EqiSVxC383Q9D",
	"SpZka+O4m91sU/9nyUNyOJz35g3tzzSUaSYFCKNp8JnqMIaU2Y8DZXiYAH7MlMxAGQ72C5abWCr8FIEO",
	"Fc8Ml4IGdC9lPCFyTEwMhEUpF+Q2liRUwAxE7m0xp0fhjqUZzk6t5X94yFj3Vqokoh5VwKIjkUxpYFQO",
	"HjXTDC21UVxM6MyjoRQGhGnxIeJGqu4HTd6cHL0lo0SG1yRihtH5LHL0AUJjZ3GeDew8lUNb/tZOx/9X",
	"Z+vVaX8r8P3A9y+oR8dSpczQgEbMQMfwFB7iKdyFoLKFFU5jIAfDwYBwTTIl84gYSZgQMhchEG40keMx",
	"DzlLSMJyEcbdbpd6NGV3hyAmJqZB3/d9j6ZczF+0rJ3lo4TruNxhM1LvYxD1MyG3TJP5CI+IPEkIH5NI",
	"sbFpHNg68cFZ2AiHufisjJdO8smys2fvDjtjxUFEyZSgiUd4muYGpyZsbEC5NEPruquYVR0Xwmb8tpbD",
	"lzFjQOFq/7tknU+DzoXfeXX1z+//HXTqzy/+8R1t89swk1t4fKdgTAP6t16FrF4Bq16BqRNnPPOo4cZB",
	"rPLZJsah9ZkMipxIMdkbG9h5wPnnWXRffm/7p/2dYPv35fcNKG3PqLZC/zfHcWFgAorOZmjyMecKIhpc",
	"ulMvo1GBpgL6PMBeST91+Na3Wrl01QL55gGg0yJP0YMyzecIwOFVzKrXLTEYWkeKqd/Bxxy0WabNGmct",
	"ufWULFEi7ilQ8wem/7oZ1pYte0q5Qrd4khGsQrodOkTDmUdT0JpNFjY6ECQXcJdBiNUR0J7IMMyVgqhL",
	"V+3H+lDN/JveDwtfyzw/EHhcLHFb8+ghT7k5ys3ReFfmIkKAHYgblvBomCttTd5K8xq/ox7dSzMz3ZXR",
	"tDIrngYJQn66d8e1cZNkuTlHA8vK5XKD3MTu81VLOpxZFD8SkNbFQUsuOn8i8og5ueAx4g/CXHEzPcHM",
	"cTtEAO4CU6AwXvhmZJ9elxT95v0p9RZqpHWShSFoTYy8BkG4IANLlvyTPQQSA4sAj8FmKfrh5q2yLTYm",
	"w2CgB0MprzmUHqxaLLTW1KMcv58/CZaWqP51MBzunZz8enr0897bakmW8Z9hSmcYCy7GcnmxgSCD4wMy",
	"loqkTLAJF5NStWj71pRMeQsjzQ1050gvPB2U1oPjg1qFCGi/63d93LDMQLCM04Bu21eW2WJ7Gr1yrd5N",
	"H58n0CKn3oFRHG5AE0YydNEmTsK1QUU8Lx+V31oqtBhNSU2mEZwURMTFBPeAWW9P7iCiAd0HU+7jvG8d",
	"VCwFA0rT4HLRH4deG53CHaeN7Ol8zEFNq8MJS6Q78mpi4L9br/KL7Tdx9NMv+uCn5CY62U1H2+f5xXDX",
	"Z/tnk4v3rz9F++fTg/1zcXH7ww9tzLXo3C/sjog8HYHC4MxDYiQZg7FFp83NBKmq4WUEY5YnBgFeK9b4",
	"kLI7niLj7ThMuod+ixC5Ql7VmRTaYW/L9xdIhmVZwkMbwN4H7bRO5cMCN7lQPnIEPWpbGGQGA+lDVSat",
	"6IYpxab4HDP9Fu7M8WI1aqi0kZQJMLFUc4o+qj7Hct3BQQvwvQcGXXTq5ZohX1l327zYZRFRrqTYRXf+",
	"jEXPxLWQt4JoUDegXJHvNlifBpdXHtV5mjI1pQE9xFAtx8m2c1K3EI8Tn0g7Am5L+y750UHDgspqW+IE",
	"dJcMbGcuRTJdpphjqZscU0TMFvnHilarXG7Lm6IxLTs7EoFhPNG0npWYuLMlCPd/B4RZde/xIJAtgKQc",
	"/iBk1HcIEdG5rajjPMHDeSpkvFwzfF+IDFZIE1S7dtVXf/yqZcBvuYmJibm2lwmEOfFKwKrXvxg9fF4S",
	"Y5fuzoxeYWVd1IrVlw1ecaBrsoRdqa5uem7ol2kcliRVKf/ecQ4TUUVmL2qaZ96v1xXPvdTUUD/WcCOB",
	"NhLoq5NAdZR8axT/3DjVarUm7Vm7F8vE+hnrzMwBNgEDy+T6o32vCRPzG/mRu+u+nxfduIoaT9xF1wIz",
	"WjLBjrbikuJGrCml2gmweSG4yG3L9PGypYcv9uS23yp1nkZ1vPzzVIeQhoxlLp4nGlwi1vIXN7lSR2gu",
	"JgksdzyY/Nw4fbZCDPwVMt7/OhqO0+r3vk36t/bf+2BQ3balo02fmb0YDFuuRN1lsSVw20fUbilXNN04",
	"35On8+P3+a23+ffkh+sJ1ujy/a+ryy96nm+8y98QziPVWwevRr1tV529gs0sCFrvEE/A1IXn33VxWYjt",
	"aI0KRUQ0WpoYGj9aGJ6CNizN1rlcRJo7LhzbFO91eKQ6kY2Ifm6gLhDxEFTn4stxPWLhdfXLAAI7TICp",
	"R4T22dy7DbjXEgliA+9nXLPL020CfOVS7Wu4ya3Xbfffx0pGeWh/OXNG1KO5Sop/eeig12MZ71Z/vO3R",
	"5WvqQxmyhERw0zZF0Osl+H0stQm2fd/v0dnV7P8BAAD//3liM+RTLAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
